### ISSUE TITLE
Main image doesn't change

### ISSUE THREAD

**Issue by UndefinedUser** [tzyganu/Switcher#119] opened 2015-06-15 02:29 UTC
Hi, Firstly thanks for make this extension available for free. Seems to be very useful. It works fine for changing thumbnail images on custom options. Main purpose of using this extension was to change main images by selecting options, but however I configure on backend, just doesn't work. Main image just stays the same. I do use custom theme, which may cause this problem and I am not so familiar about using configurable product, (but I did check thoroughly how to create one)thus would be very kind if you could show me what might cause this problem, as well as setting up configurable product.

**Comment by tzyganu** [comment] 2015-06-15 07:11
Here are the steps you need to follow. 
 - make sure the simple products associated to the configurable products have images.
 - Read the [configuration documentation](https://github.com/tzyganu/Switcher/wiki/configuration) to see what each field does and to get some idea of how you can configure the extension to fit your needs. 
 - If none of the above produce any results, revert to the default theme temporarily to see if it makes a difference.
 - If the above does not produce a valid result,  post the url of one of your configurable products inhere so I can take a look.

**Comment by UndefinedUser** [comment] 2015-06-15 08:48
Hi,

Thanks for the suggestion, it was the other extension conflicted with this. So the product images are successfully changing.
Also is there any chance we can change product title and descriptions when we select options using this extension?

Thank you,
Mas

On Jun 15, 2015, at 03:11 PM, Marius Strajeru <notifications@github.com> wrote:

Here are the steps you need to follow.
make sure the simple products associated to the configurable products have images.
Read the configuration documentation to see what each field does and to get some idea of how you can configure the extension to fit your needs.
If none of the above produce any results, revert to the default theme temporarily to see if it makes a difference.
If the above does not produce a valid result, post the url of one of your configurable products inhere so I can take a look.

**Comment by tzyganu** [comment] 2015-06-15 10:35
@UndefinedUser changing the name and description are not in the scope of this extension.  
I will close this for now since the issue was not caused by the extension itself.

**Closed by tzyganu** 2015-06-15 10:35 UTC
