### ISSUE TITLE
custom options showing the label instead of product images.

### ISSUE THREAD

**Issue by sathishraj319** [tzyganu/Switcher#109] opened 2015-05-05 15:00 UTC
Extension is working fine. Thanks for that. But in the admin configuration easylife swticher ->Transformation settings-> if we selected 'simple product images', the simple product images is not showing in the frontend instead of it showing the options label.
Please help us to solve the issue.

**Comment by tzyganu** [comment] 2015-05-06 07:19
@sathishraj319 When you select to use simple product images you need to select an image attribute to use: `image`, `small_image`, `thumbnail`. Make sure the simple products have one of these attributes set. If the simple products have these attributes set to `no_selection` there are no images to show and they will fall back to labels.

**Comment by sathishraj319** [comment] 2015-05-06 07:48
i checked the image attribute. i have selected image,small image and thumbnail. still labels is showing.

in product.js.. i console the images variable, the object is not getting.. any solution.

**Comment by sathishraj319** [comment] 2015-05-06 07:50
and also in media folder 40*40 images not creating..

**Comment by tzyganu** [comment] 2015-05-06 07:55
do you have a link to your website?

**Comment by sathishraj319** [comment] 2015-05-06 07:58
http://s292480579.websitehome.co.uk/

**Comment by tzyganu** [comment] 2015-05-06 08:12
For some reason the `images` section in the config is empty.  
You can check this by putting this in your browser console: `spConfig.config.images`. It returns an empty array (`[]`). I tested on this product http://s292480579.websitehome.co.uk/kudos-plain-table-linen-tablecloth-132-178cm-52-70.html.  
The images are retrieved in the method `Easylife_Switcher_Block_Catalog_Product_View_Type_Configurable_Config::getImages()`.  
You can start debugging from there to see why you get an empty array. I cannot reproduce this issue. It works nicely on my side.

**Comment by sathishraj319** [comment] 2015-05-06 09:39
it is not creating a 40*40 folder under media/catalog/product/cache/1/image. It there any problem..

**Comment by mat-b-** [comment] 2015-05-13 13:49
Ran into similar problem. Maybe https://github.com/tzyganu/Switcher/pull/113 can resolve this.

**Comment by tzyganu** [comment] 2015-05-25 12:48
@mat-b- I identified the problem. There is a difference in how the simple products are retrieved in 1.9.1 and the rest of the versions.  
See the difference here:
for 1.9.1: https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Catalog/Model/Product/Type/Configurable.php#L344
for 1.8: https://github.com/OpenMage/magento-mirror/blob/magento-1.8/app/code/core/Mage/Catalog/Model/Product/Type/Configurable.php#L337

It seams that `->addAttributeToSelect('*')` was removed. I will see how I can overcome it and come back with a solution soon.

**Comment by tzyganu** [comment] 2015-05-25 13:29
@mat-b- I just released a new version. this should be fixed now. If the problem still reproduces please write a comment here and I will reopen it.

**Closed by tzyganu** 2015-05-25 13:29 UTC

**Comment by mat-b-** [comment] 2015-05-25 17:05
Thank you!
