### ISSUE TITLE
Image not found 404

### ISSUE THREAD

**Issue by starkdany** [tzyganu/Switcher#135] opened 2015-08-17 20:16 UTC
Hi, first of all, great work man, its a really good extension! Its giving me some trouble, though:

I have selected for it to switch all media section, and it works. Except for the "more views" part. When I click an image from that section it shows a 404 page. Any pointers on how to change the links that are generated?
Right now it appears to be searching for url/catalog/product/gallery/id/
I think it should be: url/media/catalog/product/gallery/id/

Thanks man!

**Comment by tzyganu** [comment] 2015-08-19 10:35
@starkdany  This extension does not alter the media block in any way. It just loads it and displays it as it it. 
By default this extension uses the default media block and template of Magento
If you have an extension that changes the media block and you have to configure the Easylife_Switcher to use it. You can do that from the system->configuration section by changing the fields `Media block alias` and `Media block template`. For more details on what these fields do, check the [documentation](https://github.com/tzyganu/Switcher/wiki/configuration).  
I will close this issue for now since I cannot reproduce it. If you find something new, or if you can provide the steps to reproduce it, I will reopen it.

**Closed by tzyganu** 2015-08-19 10:35 UTC
