### ISSUE TITLE
Images not switching after an image has been chosen from the media block

### ISSUE THREAD

**Issue by margsenjo** [tzyganu/Switcher#128] opened 2015-07-07 19:30 UTC
The extension works good for my shop until I manually click on a product image from the media block below the view image. After that, the switch doesn't work anymore. Neither the dropdown nor the custom switcher images.

Is there a way to fix this?

**Comment by tzyganu** [comment] 2015-07-09 19:03
@margsenjo Is there a link where I can see this behavior? I cannot reproduce it. I'll take a shot in the dark and say that when clicking on the product image some js is triggered and there is an error somewhere. That's all I can think of right now.

**Comment by margsenjo** [comment] 2015-07-16 15:48
You can check it here: http://urban-zweirad.de/harper-bike-advanced.html

Please let me know if there's a possibility to change the called js in the switcher setup.

**Comment by tzyganu** [comment] 2015-07-16 20:27
@margsenjo The image actually changes, You don't see the change because the main image is hidden when you click on a small thumbnail. If you inspect the dom you will see that the src changes for the main image.  
It seams that this extension and the owlCarousel you use are not compatible.  
Sorry but I can't help you more on this.  
I don't know how owlCarousel works.
I will close this issue since it is not a problem with the extension itself.

**Closed by tzyganu** 2015-07-16 20:27 UTC

**Comment by jarnail104** [comment] 2015-08-27 12:10
@tzyganu   I am having this issue when I manually click on a product image from the media block below the view image. It open that image. And other thing is Zoom functionality on main image is also not working. Except this extension is doing great work.
Link: http://dev.ibywind.com/default/test-config-product.html

@tzyganu ...can i get reply here or should i post new question? thanks for your time
